"use client";

import Image from "next/image";
import Link from "next/link";
import {useParams} from "next/navigation";
import {FormEvent, useEffect, useMemo, useState} from "react";
import {ArrowLeft, Check, Eye, FileText, LoaderCircle, LockKeyhole, LogOut, Pencil, Plus, Save, Search, Trash2, Upload, X} from "lucide-react";
import type {FirebaseSession} from "@/lib/firebase-rest";
import {firebaseIsConfigured, readableFirebaseError, signInAdmin} from "@/lib/firebase-rest";
import {deleteNewsArticle, listNewsArticles, type NewsArticleRecord, saveNewsArticle, uploadNewsCover} from "@/lib/news-firebase";
import RichTextEditor from "../knowledge/RichTextEditor";

const SESSION_KEY = "sesan-knowledge-admin-session";
const AUTOSAVE_KEY = "sesan-news-admin-autosave";
const categories = ["Company News", "Sesan App Updates", "Events & Programs", "Partnerships", "Milestones", "Announcements"];
const categoryKm: Record<string,string> = {"Company News":"ព័ត៌មានក្រុមហ៊ុន","Sesan App Updates":"បច្ចុប្បន្នភាព Sesan App","Events & Programs":"ព្រឹត្តិការណ៍ និងកម្មវិធី",Partnerships:"ដៃគូសហការ",Milestones:"សមិទ្ធផលសំខាន់ៗ",Announcements:"សេចក្តីជូនដំណឹង"};

function emptyArticle(): NewsArticleRecord { const now = new Date().toISOString(); return {id: crypto.randomUUID(),titleKm:"",titleEn:"",summaryKm:"",summaryEn:"",contentKm:"",contentEn:"",category:categories[0],coverImage:"",status:"draft",featured:false,views:0,publishedAt:"",updatedAt:now}; }

export default function NewsAdminPage() {
  const params = useParams<{locale:string}>(); const locale = params.locale === "en" ? "en" : "km";
  const [session,setSession] = useState<FirebaseSession|null>(null); const [authLoading,setAuthLoading]=useState(true);
  const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [error,setError]=useState("");
  const [articles,setArticles]=useState<NewsArticleRecord[]>([]); const [editing,setEditing]=useState<NewsArticleRecord|null>(null);
  const [language,setLanguage]=useState<"km"|"en">("km"); const [query,setQuery]=useState(""); const [saving,setSaving]=useState(false); const [uploading,setUploading]=useState(false); const [notice,setNotice]=useState(false);

  useEffect(()=>{try{const raw=sessionStorage.getItem(SESSION_KEY);if(raw){const parsed=JSON.parse(raw) as FirebaseSession;if(parsed.expiresAt>Date.now()+30000)setSession(parsed);}}catch{}finally{setAuthLoading(false);}},[]);
  useEffect(()=>{if(!session)return;listNewsArticles(session).then(setArticles).catch((e)=>setError(readableFirebaseError(e)));},[session]);
  useEffect(()=>{if(!editing)return;const timer=setTimeout(()=>localStorage.setItem(AUTOSAVE_KEY,JSON.stringify(editing)),1200);return()=>clearTimeout(timer);},[editing]);

  async function login(e:FormEvent){e.preventDefault();setAuthLoading(true);setError("");try{const s=await signInAdmin(email.trim(),password);sessionStorage.setItem(SESSION_KEY,JSON.stringify(s));setSession(s);setPassword("");}catch(err){setError(readableFirebaseError(err));}finally{setAuthLoading(false);}}
  function logout(){sessionStorage.removeItem(SESSION_KEY);setSession(null);setArticles([]);}
  function update<K extends keyof NewsArticleRecord>(key:K,value:NewsArticleRecord[K]){setEditing((a)=>a?{...a,[key]:value}:a);}
  async function save(e:FormEvent){e.preventDefault();if(!editing||!session||!editing.titleKm.trim()||!editing.titleEn.trim())return;const now=new Date().toISOString();const next={...editing,updatedAt:now,publishedAt:editing.status==="published"?(editing.publishedAt||now):editing.publishedAt};setSaving(true);setError("");try{await saveNewsArticle(session,next);setArticles((xs)=>xs.some((x)=>x.id===next.id)?xs.map((x)=>x.id===next.id?next:x):[next,...xs]);localStorage.removeItem(AUTOSAVE_KEY);setEditing(null);setNotice(true);setTimeout(()=>setNotice(false),2200);}catch(err){setError(readableFirebaseError(err));}finally{setSaving(false);}}
  async function remove(article:NewsArticleRecord){if(!session||!confirm(`លុប “${article.titleKm || article.titleEn}” មែនទេ?`))return;try{await deleteNewsArticle(session,article.id);setArticles((xs)=>xs.filter((x)=>x.id!==article.id));}catch(err){setError(readableFirebaseError(err));}}
  async function upload(file?:File){if(!file||!session||!editing)return;if(!file.type.startsWith("image/")||file.size>5*1024*1024){setError("សូមជ្រើសរើសរូបភាពតិចជាង 5MB។");return;}setUploading(true);try{update("coverImage",await uploadNewsCover(session,file));}catch(err){setError(readableFirebaseError(err));}finally{setUploading(false);}}
  const filtered=useMemo(()=>{const q=query.toLowerCase().trim();return articles.filter((a)=>!q||a.titleKm.toLowerCase().includes(q)||a.titleEn.toLowerCase().includes(q)||a.category.toLowerCase().includes(q));},[articles,query]);

  if(!firebaseIsConfigured()) return <Gate><p className="font-black text-red-600">Firebase is not configured.</p></Gate>;
  if(authLoading) return <Gate><LoaderCircle className="mx-auto h-9 w-9 animate-spin text-green-600" /></Gate>;
  if(!session) return <Gate><div className="text-center"><LockKeyhole className="mx-auto h-10 w-10 text-green-700"/><h1 className="mt-4 text-2xl font-black">News Admin</h1><p className="mt-2 text-sm text-slate-500">ប្រើគណនី Sesan Knowledge Admin ដដែល។</p></div>{error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{error}</p>}<form onSubmit={login} className="mt-6 space-y-4"><input className="w-full rounded-xl border border-slate-200 px-4 py-3" type="email" required placeholder="Admin email" value={email} onChange={(e)=>setEmail(e.target.value)}/><input className="w-full rounded-xl border border-slate-200 px-4 py-3" type="password" required placeholder="Password" value={password} onChange={(e)=>setPassword(e.target.value)}/><button className="w-full rounded-xl bg-green-600 px-4 py-3 font-black text-white">ចូលគ្រប់គ្រង</button></form></Gate>;

  return <main className="min-h-screen bg-slate-100 text-slate-950"><header className="border-b bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4"><div><p className="font-black text-green-700">SESAN GROUP</p><p className="text-sm font-bold text-slate-500">News & Updates Admin</p></div><div className="flex gap-2"><Link href={`/${locale}/news`} className="rounded-xl border px-3 py-2 text-sm font-bold"><Eye className="inline h-4 w-4"/> News</Link><button onClick={logout} className="rounded-xl border px-3 py-2 text-sm font-bold"><LogOut className="inline h-4 w-4"/></button></div></div></header>
  <div className="mx-auto max-w-7xl px-5 py-8"><Link href={`/${locale}`} className="inline-flex items-center gap-2 text-sm font-bold text-slate-500"><ArrowLeft className="h-4 w-4"/>ទំព័រដើម</Link><div className="mt-5 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-black uppercase tracking-widest text-green-700">News Management</p><h1 className="mt-2 text-3xl font-black">ព័ត៌មាន និងបច្ចុប្បន្នភាព</h1><p className="mt-2 text-slate-600">បង្កើត កែប្រែ និងផ្សព្វផ្សាយព័ត៌មាន Sesan ជាខ្មែរ និងអង់គ្លេស។</p></div><button onClick={()=>{setLanguage("km");setEditing(emptyArticle());}} className="rounded-xl bg-green-600 px-5 py-3 font-black text-white"><Plus className="inline h-5 w-5"/> បន្ថែមព័ត៌មាន</button></div>
  {notice&&<p className="mt-5 rounded-xl bg-green-50 p-4 font-bold text-green-800"><Check className="inline h-5 w-5"/> បានរក្សាទុក។</p>}{error&&<p className="mt-5 rounded-xl bg-red-50 p-4 font-bold text-red-700">{error}</p>}
  <div className="mt-7 grid gap-4 sm:grid-cols-3"><Stat label="ព័ត៌មានសរុប" value={articles.length}/><Stat label="បានផ្សព្វផ្សាយ" value={articles.filter((a)=>a.status==="published").length}/><Stat label="ព្រាង" value={articles.filter((a)=>a.status==="draft").length}/></div>
  <div className="mt-7 rounded-2xl bg-white p-4 ring-1 ring-slate-200"><div className="relative"><Search className="absolute left-3 top-3 h-5 w-5 text-slate-400"/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="ស្វែងរកព័ត៌មាន..." className="w-full rounded-xl border border-slate-200 py-2.5 pl-10 pr-4"/></div></div>
  <div className="mt-5 space-y-3">{filtered.map((a)=><div key={a.id} className="flex flex-col gap-4 rounded-2xl bg-white p-5 ring-1 ring-slate-200 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex flex-wrap gap-2"><span className="rounded-full bg-green-50 px-3 py-1 text-xs font-black text-green-700">{categoryKm[a.category]??a.category}</span><span className={`rounded-full px-3 py-1 text-xs font-black ${a.status==="published"?"bg-sky-50 text-sky-700":"bg-amber-50 text-amber-700"}`}>{a.status}</span></div><h2 className="mt-2 font-black">{a.titleKm||a.titleEn}</h2><p className="mt-1 text-sm text-slate-500">{a.views.toLocaleString()} views</p></div><div className="flex gap-2"><button onClick={()=>{setLanguage("km");setEditing(a);}} className="rounded-xl border px-3 py-2 text-sm font-bold"><Pencil className="inline h-4 w-4"/> កែ</button><button onClick={()=>remove(a)} className="rounded-xl border border-red-200 px-3 py-2 text-sm font-bold text-red-600"><Trash2 className="inline h-4 w-4"/></button></div></div>)}</div></div>
  {editing&&<div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/60 p-3 sm:p-6"><form onSubmit={save} className="mx-auto max-w-5xl rounded-3xl bg-white p-5 shadow-2xl sm:p-7"><div className="flex items-center justify-between"><h2 className="text-xl font-black">{editing.titleKm||"ព័ត៌មានថ្មី"}</h2><button type="button" onClick={()=>setEditing(null)}><X className="h-6 w-6"/></button></div><div className="mt-5 flex gap-2"><button type="button" onClick={()=>setLanguage("km")} className={`rounded-xl px-4 py-2 font-black ${language==="km"?"bg-green-600 text-white":"bg-slate-100"}`}>ខ្មែរ</button><button type="button" onClick={()=>setLanguage("en")} className={`rounded-xl px-4 py-2 font-black ${language==="en"?"bg-green-600 text-white":"bg-slate-100"}`}>English</button></div>
  <div className="mt-5 grid gap-5"><label className="font-bold">ចំណងជើង {language==="km"?"ខ្មែរ":"English"}<input required value={language==="km"?editing.titleKm:editing.titleEn} onChange={(e)=>update(language==="km"?"titleKm":"titleEn",e.target.value)} className="mt-2 w-full rounded-xl border p-3 font-normal"/></label><label className="font-bold">សេចក្តីសង្ខេប<textarea value={language==="km"?editing.summaryKm:editing.summaryEn} onChange={(e)=>update(language==="km"?"summaryKm":"summaryEn",e.target.value)} rows={3} className="mt-2 w-full rounded-xl border p-3 font-normal"/></label><div><p className="mb-2 font-bold">ខ្លឹមសារ</p><RichTextEditor value={language==="km"?editing.contentKm:editing.contentEn} onChange={(value)=>update(language==="km"?"contentKm":"contentEn",value)} /></div>
  <div className="grid gap-4 sm:grid-cols-2"><label className="font-bold">ប្រភេទ<select value={editing.category} onChange={(e)=>update("category",e.target.value)} className="mt-2 w-full rounded-xl border p-3 font-normal">{categories.map((c)=><option key={c} value={c}>{categoryKm[c]} / {c}</option>)}</select></label><label className="font-bold">ស្ថានភាព<select value={editing.status} onChange={(e)=>update("status",e.target.value as "draft"|"published")} className="mt-2 w-full rounded-xl border p-3 font-normal"><option value="draft">Draft</option><option value="published">Published</option></select></label></div>
  <label className="flex items-center gap-3 font-bold"><input type="checkbox" checked={editing.featured} onChange={(e)=>update("featured",e.target.checked)} className="h-5 w-5"/> Featured News</label><div><p className="font-bold">Cover Image</p>{editing.coverImage&&<Image src={editing.coverImage} alt="Cover" width={320} height={180} unoptimized className="mt-2 rounded-xl object-cover"/>}<label className="mt-3 inline-flex cursor-pointer items-center gap-2 rounded-xl border px-4 py-2 font-bold"><Upload className="h-4 w-4"/>{uploading?"Uploading...":"Upload image"}<input type="file" accept="image/*" className="hidden" onChange={(e)=>upload(e.target.files?.[0])}/></label></div></div>
  <div className="mt-7 flex justify-end gap-3"><button type="button" onClick={()=>setEditing(null)} className="rounded-xl border px-5 py-3 font-black">Cancel</button><button disabled={saving} className="rounded-xl bg-green-600 px-5 py-3 font-black text-white disabled:opacity-50"><Save className="inline h-5 w-5"/> {saving?"Saving...":"Save"}</button></div></form></div>}</main>;
}

function Gate({children}:{children:React.ReactNode}){return <main className="min-h-screen bg-slate-100 px-5 py-16"><div className="mx-auto max-w-md rounded-3xl bg-white p-7 shadow-sm ring-1 ring-slate-200">{children}</div></main>}
function Stat({label,value}:{label:string;value:number}){return <div className="rounded-2xl bg-white p-5 ring-1 ring-slate-200"><FileText className="h-5 w-5 text-green-700"/><p className="mt-3 text-3xl font-black">{value}</p><p className="mt-1 text-sm font-bold text-slate-500">{label}</p></div>}
