import type {Metadata} from "next";
import Link from "next/link";
import {notFound} from "next/navigation";
import {ArrowLeft, ArrowRight, BadgeCheck, Banknote, BarChart3, Check, Clock3, GraduationCap, ShieldCheck, Upload, WalletCards} from "lucide-react";
import {CREATOR_SHARE_RATE, MINIMUM_WITHDRAWAL_RIEL, PAYOUT_HOLD_DAYS, splitAcademySale} from "@/lib/academy";

type PageProps = {params: Promise<{locale: string}>};

export async function generateMetadata({params}: PageProps): Promise<Metadata> {
  const {locale} = await params;
  return {title: locale === "km" ? "Creator Center | Sesan Academy" : "Creator Center | Sesan Academy", description: locale === "km" ? "បង្កើត និងលក់មេរៀនវីដេអូនៅ Sesan Academy។" : "Create and sell video lessons on Sesan Academy."};
}

export default async function CreatorPage({params}: PageProps) {
  const {locale: rawLocale} = await params;
  if (rawLocale !== "km" && rawLocale !== "en") notFound();
  const locale = rawLocale as "km" | "en";
  const text = (en: string, km: string) => locale === "km" ? km : en;
  const example = splitAcademySale(5_000);

  return (
    <main className="min-h-screen bg-slate-50 text-slate-950">
      <header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4"><Link href={`/${locale}/academy`} className="flex items-center gap-3"><img src="/sesan-logo.png" alt="Sesan" className="h-11 w-11 object-contain" /><div><p className="font-black text-green-700">SESAN ACADEMY</p><p className="text-xs font-bold text-slate-400">CREATOR CENTER</p></div></Link><Link href={`/${locale}/academy`} className="inline-flex items-center gap-2 rounded-full border border-slate-200 px-4 py-2.5 text-sm font-bold text-slate-600 hover:text-green-700"><ArrowLeft className="h-4 w-4" />{text("Academy", "Academy")}</Link></div></header>

      <section className="overflow-hidden bg-gradient-to-br from-slate-950 via-slate-900 to-green-950 px-5 py-20 text-white"><div className="mx-auto grid max-w-6xl items-center gap-12 lg:grid-cols-[1.1fr_0.9fr]"><div><span className="inline-flex items-center gap-2 rounded-full border border-green-400/30 bg-green-400/10 px-4 py-2 text-sm font-black text-green-300"><GraduationCap className="h-4 w-4" />CREATOR CENTER</span><h1 className="mt-6 text-5xl font-black leading-tight">{text("Teach what you know.", "បង្រៀនអ្វីដែលអ្នកចេះ។")}<span className="block text-green-400">{text("Earn every time students learn.", "ទទួលចំណូលពេលសិស្សទិញមេរៀន។")}</span></h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-300">{text("Create practical video lessons, reach Cambodian learners and keep 70% of every completed sale.", "បង្កើតមេរៀនវីដេអូដែលមានប្រយោជន៍ ទៅដល់អ្នករៀនកម្ពុជា និងទទួលបាន 70% ពីការលក់នីមួយៗ។")}</p><a href="mailto:info@sesanshop.com?subject=Sesan%20Academy%20Creator%20Application" className="mt-8 inline-flex items-center gap-2 rounded-full bg-green-500 px-7 py-4 font-black text-white transition hover:bg-green-400">{text("Request creator access", "ស្នើសុំក្លាយជា Creator")}<ArrowRight className="h-5 w-5" /></a></div><div className="rounded-[32px] border border-white/10 bg-white/10 p-7 backdrop-blur"><p className="text-sm font-black uppercase tracking-[0.18em] text-green-300">{text("Example: 5,000៛ sale", "ឧទាហរណ៍៖ លក់បាន 5,000៛")}</p><div className="mt-6 space-y-4"><MoneyRow label={text("Customer pays", "អ្នកទិញបង់")} amount={example.gross} /><MoneyRow label={text("Creator receives (70%)", "Creator ទទួល (70%)")} amount={example.creatorEarning} highlight /><MoneyRow label={text("Sesan commission (30%)", "កម្រៃ Sesan (30%)")} amount={example.sesanCommission} /></div><div className="mt-6 rounded-2xl bg-slate-950/50 p-4 text-sm leading-6 text-slate-300">{text(`Earnings remain pending for ${PAYOUT_HOLD_DAYS} days, then become available for withdrawal.`, `ចំណូលស្ថិតក្នុង Pending ${PAYOUT_HOLD_DAYS} ថ្ងៃ រួចទើបអាចដកបាន។`)}</div></div></div></section>

      <section className="bg-green-50 px-5 py-8"><div className="mx-auto flex max-w-6xl flex-col items-center justify-between gap-5 rounded-[28px] border border-green-200 bg-white p-7 md:flex-row"><div><h2 className="text-2xl font-black">{text("Ready to become a Creator?", "ត្រៀមក្លាយជា Creator ហើយឬនៅ?")}</h2><p className="mt-2 text-slate-500">{text("Create an account, submit your application and track approval online.", "បង្កើតគណនី ដាក់ពាក្យ និងតាមដានការអនុម័តតាម Website។")}</p></div><Link href={`/${locale}/academy/creator/dashboard`} className="inline-flex shrink-0 items-center gap-2 rounded-full bg-green-600 px-6 py-3.5 font-black text-white hover:bg-green-500">{text("Apply or login", "ដាក់ពាក្យ ឬចូលគណនី")}<ArrowRight className="h-5 w-5" /></Link></div></section>

      <section className="px-5 py-20"><div className="mx-auto max-w-6xl"><div className="text-center"><p className="text-sm font-black uppercase tracking-[0.2em] text-green-700">{text("How it works", "របៀបដំណើរការ")}</p><h2 className="mt-3 text-4xl font-black">{text("From knowledge to income", "ពីចំណេះដឹងទៅជាចំណូល")}</h2></div><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-4"><Step icon={BadgeCheck} number="1" title={text("Get approved", "ទទួលការអនុម័ត")} description={text("Create your creator profile and complete verification.", "បង្កើត Profile និងបំពេញការផ្ទៀងផ្ទាត់។")} /><Step icon={Upload} number="2" title={text("Upload lessons", "Upload មេរៀន")} description={text("Add videos, a cover, description and your price.", "ដាក់វីដេអូ រូបគម្រប ព័ត៌មាន និងតម្លៃ។")} /><Step icon={BarChart3} number="3" title={text("Track sales", "មើលការលក់")} description={text("See students, sales and earnings in your dashboard.", "មើលសិស្ស ការលក់ និងចំណូលក្នុង Dashboard។")} /><Step icon={WalletCards} number="4" title={text("Withdraw", "ដកប្រាក់")} description={text(`Request payout from ${MINIMUM_WITHDRAWAL_RIEL.toLocaleString()}៛.`, `ស្នើដកចាប់ពី ${MINIMUM_WITHDRAWAL_RIEL.toLocaleString()}៛។`)} /></div></div></section>

      <section className="bg-white px-5 py-20"><div className="mx-auto grid max-w-6xl gap-8 lg:grid-cols-2"><div className="rounded-[30px] border border-slate-200 p-8"><ShieldCheck className="h-10 w-10 text-green-700" /><h2 className="mt-5 text-2xl font-black">{text("Creator requirements", "លក្ខខណ្ឌ Creator")}</h2><div className="mt-6 space-y-4">{[text("Original lessons or content you have permission to sell", "មេរៀនផ្ទាល់ខ្លួន ឬមានសិទ្ធិលក់ត្រឹមត្រូវ"), text("Clear audio and useful, honest instruction", "សំឡេងច្បាស់ និងបង្រៀនមានប្រយោជន៍"), text("No copied, illegal or misleading content", "មិនចម្លង មិនខុសច្បាប់ និងមិនបោកប្រាស់"), text("A verified payment account for payouts", "មានគណនីទទួលប្រាក់ដែលបានផ្ទៀងផ្ទាត់")].map((item) => <p key={item} className="flex gap-3 text-slate-600"><Check className="mt-0.5 h-5 w-5 shrink-0 text-green-600" />{item}</p>)}</div></div><div className="rounded-[30px] bg-slate-950 p-8 text-white"><Banknote className="h-10 w-10 text-amber-300" /><h2 className="mt-5 text-2xl font-black">{text("Transparent earnings", "ចំណូលច្បាស់លាស់")}</h2><div className="mt-6 grid grid-cols-2 gap-4"><MiniStat icon={BarChart3} value={`${Math.round(CREATOR_SHARE_RATE * 100)}%`} label={text("Your share", "ចំណែករបស់អ្នក")} /><MiniStat icon={Clock3} value={`${PAYOUT_HOLD_DAYS} days`} label="Pending" /><MiniStat icon={WalletCards} value={`${MINIMUM_WITHDRAWAL_RIEL.toLocaleString()}៛`} label={text("Minimum payout", "ដកអប្បបរមា")} /><MiniStat icon={ShieldCheck} value="100%" label={text("Sales history", "ប្រវត្តិការលក់")} /></div></div></div></section>
    </main>
  );
}

function MoneyRow({label, amount, highlight = false}: {label: string; amount: number; highlight?: boolean}) {return <div className={`flex items-center justify-between rounded-2xl px-5 py-4 ${highlight ? "bg-green-400 text-slate-950" : "bg-white/10"}`}><span className="font-bold">{label}</span><strong className="text-xl">{amount.toLocaleString()}៛</strong></div>;}
function Step({icon: Icon, number, title, description}: {icon: typeof Upload; number: string; title: string; description: string}) {return <article className="rounded-[26px] border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><span className="rounded-2xl bg-green-100 p-3 text-green-700"><Icon className="h-6 w-6" /></span><span className="text-3xl font-black text-slate-200">{number}</span></div><h3 className="mt-5 text-xl font-black">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-500">{description}</p></article>;}
function MiniStat({icon: Icon, value, label}: {icon: typeof BarChart3; value: string; label: string}) {return <div className="rounded-2xl bg-white/10 p-4"><Icon className="h-5 w-5 text-green-300" /><p className="mt-3 text-xl font-black">{value}</p><p className="mt-1 text-xs font-bold text-slate-400">{label}</p></div>;}
