import type {Metadata} from "next";
import Link from "next/link";
import {notFound, redirect} from "next/navigation";
import {ArrowLeft, FileText} from "lucide-react";

type PageProps = {params: Promise<{locale: string}>};
type Subsection = {title: string; paragraphs?: string[]; bullets?: string[]};
type TermSection = {number: string; id: string; title: string; paragraphs: string[]; bullets?: string[]; subsections?: Subsection[]; note?: string};

export const metadata: Metadata = {
  title: "លក្ខខណ្ឌប្រើប្រាស់ | Sesan Group",
  description: "លក្ខខណ្ឌប្រើប្រាស់ពេញលេញសម្រាប់ Sesan App, Sesan Shop, Website និងសេវាកម្មរបស់ Sesan Group។",
};

const sections: TermSection[] = [
  {number:"០១",id:"acceptance",title:"ការទទួលយកលក្ខខណ្ឌ",paragraphs:["លក្ខខណ្ឌប្រើប្រាស់នេះជាកិច្ចព្រមព្រៀងរវាងអ្នក និង Sesan Group («Sesan», «យើង», «របស់យើង») សម្រាប់ការចូលប្រើ Sesan App, Sesan Shop, Website, ទីផ្សារឌីជីថល និងសេវាកម្មពាក់ព័ន្ធ។","ដោយបង្កើតគណនី ចូលមើល ឬប្រើសេវា អ្នកបញ្ជាក់ថាបានអាន យល់ និងយល់ព្រមគោរពលក្ខខណ្ឌនេះ ព្រមទាំងគោលការណ៍ឯកជនភាព។ បើអ្នកមិនយល់ព្រម សូមកុំប្រើសេវា។"]},
  {number:"០២",id:"eligibility",title:"សិទ្ធិ និងលក្ខណៈសម្បត្តិអ្នកប្រើ",paragraphs:["អ្នកត្រូវមានសមត្ថភាពស្របច្បាប់ក្នុងការធ្វើកិច្ចព្រមព្រៀង។ អនីតិជនត្រូវប្រើក្រោមការត្រួតពិនិត្យ និងការយល់ព្រមរបស់មាតាបិតា ឬអាណាព្យាបាលស្របច្បាប់។","បើអ្នកប្រើសេវាជំនួសអាជីវកម្ម អង្គការ ឬបុគ្គលផ្សេង អ្នកធានាថាមានសិទ្ធិចងភ្ជាប់ភាគីនោះនឹងលក្ខខណ្ឌនេះ។"]},
  {number:"០៣",id:"accounts",title:"គណនីអ្នកប្រើ",paragraphs:["មុខងារខ្លះតម្រូវឱ្យបង្កើតគណនីដោយផ្ដល់ព័ត៌មានត្រឹមត្រូវ ពេញលេញ និងទាន់សម័យ។ អ្នកទទួលខុសត្រូវចំពោះសកម្មភាពទាំងអស់ក្រោមគណនីរបស់ខ្លួន។"],bullets:["រក្សា Password, PIN និង OTP ជាសម្ងាត់ និងមិនចែករំលែកឱ្យអ្នកដទៃ។","ប្រើលេខទូរស័ព្ទ ឬព័ត៌មានទំនាក់ទំនងដែលអ្នកមានសិទ្ធិប្រើ។","ជូនដំណឹង Sesan ភ្លាមៗ បើសង្ស័យថាគណនីត្រូវបានចូលដោយគ្មានសិទ្ធិ។","កុំបង្កើតគណនីក្លែងក្លាយ ធ្វើជាអ្នកដទៃ ឬរំលងការផ្អាកគណនី។"],note:"Sesan អាចស្នើឯកសារ ឬព័ត៌មានបន្ថែម ដើម្បីផ្ទៀងផ្ទាត់គណនី អាជីវកម្ម ផលិតផល ឬប្រតិបត្តិការ។"},
  {number:"០៤",id:"marketplace",title:"លក្ខណៈរបស់ទីផ្សារ",paragraphs:["Sesan ផ្ដល់បច្ចេកវិទ្យាដើម្បីភ្ជាប់អ្នកទិញ អ្នកលក់ កសិករ ម្ចាស់ដេប៉ូ និងអ្នកផ្ដល់សេវា។ លុះត្រាតែបានបញ្ជាក់ជាក់លាក់ Sesan មិនមែនជាម្ចាស់ អ្នកផលិត អ្នកលក់ ឬអ្នកធានាផលិតផលដែលបង្ហោះដោយអ្នកប្រើទេ។","កិច្ចព្រមព្រៀងទិញលក់កើតឡើងរវាងអ្នកទិញ និងអ្នកលក់។ Sesan អាចជួយផ្ដល់ព័ត៌មាន ឧបករណ៍ និងការដោះស្រាយបញ្ហា ប៉ុន្តែមិនធានាថាភាគីណាមួយនឹងបំពេញកាតព្វកិច្ចរបស់ខ្លួនទេ។"]},
  {number:"០៥",id:"seller",title:"កាតព្វកិច្ចរបស់អ្នកលក់",paragraphs:["អ្នកលក់ទទួលខុសត្រូវទាំងស្រុងចំពោះផលិតផល ការផ្សាយ តម្លៃ ស្តុក គុណភាព សុវត្ថិភាព ភាពស្របច្បាប់ និងការបំពេញការបញ្ជាទិញ។"],bullets:["បង្ហាញឈ្មោះ រូបភាព ការពិពណ៌នា តម្លៃ និងបរិមាណឱ្យត្រឹមត្រូវ។","មានសិទ្ធិស្របច្បាប់ក្នុងការលក់ផលិតផល ឬផ្ដល់សេវា។","គោរពច្បាប់ អាជ្ញាបណ្ណ ពន្ធ ស្តង់ដារសុវត្ថិភាព និងតម្រូវការវេចខ្ចប់។","ធ្វើបច្ចុប្បន្នភាពស្តុក និងដកការផ្សាយដែលលែងមាន។","ឆ្លើយតបអ្នកទិញ និងបំពេញការបញ្ជាទិញតាមពេលសមរម្យ។","មិនបង្ហោះទំនិញក្លែងក្លាយ ហាមឃាត់ គ្រោះថ្នាក់ ឬបំភាន់។"]},
  {number:"០៦",id:"buyer",title:"កាតព្វកិច្ចរបស់អ្នកទិញ",paragraphs:["អ្នកទិញត្រូវពិនិត្យព័ត៌មានផលិតផល អ្នកលក់ តម្លៃ បរិមាណ ទីតាំង និងលក្ខខណ្ឌដឹកជញ្ជូនមុនបញ្ជាទិញ។"],bullets:["ផ្ដល់ព័ត៌មានទំនាក់ទំនង និងដឹកជញ្ជូនត្រឹមត្រូវ។","បង់ប្រាក់តាមចំនួន និងវិធីដែលបានព្រមព្រៀង។","ត្រៀមទទួលទំនិញ និងពិនិត្យនៅពេលប្រគល់។","ប្រើសារ និងប្រព័ន្ធរាយការណ៍ដោយសុចរិត។","មិនធ្វើការបញ្ជាទិញក្លែងក្លាយ បោកប្រាស់ ឬមានគោលបំណងរំខាន។"]},
  {number:"០៧",id:"payments",title:"តម្លៃ កម្រៃ និងការទូទាត់",paragraphs:["តម្លៃផលិតផលត្រូវកំណត់ដោយអ្នកលក់ លុះត្រាតែ Sesan ជាអ្នកលក់ដោយផ្ទាល់។ តម្លៃអាចរួម ឬមិនរួមថ្លៃដឹកជញ្ជូន ពន្ធ និងកម្រៃផ្សេងៗ ដូច្នេះអ្នកត្រូវពិនិត្យមុនបញ្ជាក់។","ការបើកដេប៉ូនៅលើ Sesan មិនគិតកម្រៃ។ សម្រាប់ការលក់តាម Cart, Sesan អាចកាត់កម្រៃសេវា ៧% នៃតម្លៃប្រតិបត្តិការ ឬតាមអត្រាដែលបានជូនដំណឹងនៅពេលប្រើ។ កម្រៃសម្រាប់សេវាផ្សេងនឹងត្រូវបង្ហាញឱ្យដឹងជាមុន។"],subsections:[{title:"ការទូទាត់តាមភាគីទីបី",paragraphs:["ការទូទាត់អាចដំណើរការដោយធនាគារ Payment gateway ឬអ្នកផ្ដល់សេវាភាគីទីបី។ ការប្រើសេវានោះស្ថិតក្រោមលក្ខខណ្ឌ កម្រៃ និងគោលការណ៍របស់ពួកគេ។ Sesan មិនរក្សាទុក PIN ឬ OTP របស់ធនាគារអ្នកទេ។"]},{title:"ការបង្វិលប្រាក់",paragraphs:["ការបង្វិលប្រាក់អាស្រ័យលើស្ថានភាពបញ្ជាទិញ ការព្រមព្រៀងរវាងភាគី គោលការណ៍របស់អ្នកផ្ដល់ការទូទាត់ និងច្បាប់អនុវត្ត។ កម្រៃដែលបានកើតឡើងរួចអាចមិនអាចបង្វិលបាន។"]}]},
  {number:"០៨",id:"orders",title:"ការបញ្ជាទិញ និងការលុបចោល",paragraphs:["ការដាក់បញ្ជាទិញជាសំណើទិញ មិនមែនជាការធានាថាអ្នកលក់បានទទួលយកទេ។ ការបញ្ជាទិញអាចត្រូវបញ្ជាក់ បដិសេធ កែប្រែ ឬលុបចោល ដោយសារស្តុក តម្លៃ ការដឹកជញ្ជូន ការផ្ទៀងផ្ទាត់ ឬបញ្ហាសុវត្ថិភាព។","អ្នកគួរលុបចោលឱ្យបានឆាប់តាមមុខងារដែលមាន ឬទាក់ទងអ្នកលក់។ បន្ទាប់ពីរៀបចំ ឬដឹកទំនិញ អ្នកលក់អាចបដិសេធការលុបចោល ឬគិតថ្លៃដែលបានកើតឡើងសមស្រប។"]},
  {number:"០៩",id:"delivery",title:"ការដឹកជញ្ជូន",paragraphs:["ពេលវេលា និងថ្លៃដឹកជញ្ជូនគ្រាន់តែជាការប៉ាន់ស្មាន លុះត្រាតែមានការធានាជាលាយលក្ខណ៍អក្សរ។ ការពន្យារពេលអាចកើតពីអាកាសធាតុ ចរាចរណ៍ ទីតាំងមិនត្រឹមត្រូវ កង្វះស្តុក ឬហេតុការណ៍ក្រៅការគ្រប់គ្រង។","អ្នកទិញត្រូវផ្ដល់ទីតាំងត្រឹមត្រូវ និងអាចទាក់ទងបាន។ ហានិភ័យនៃទំនិញអាចផ្ទេរតាមការព្រមព្រៀងរវាងអ្នកទិញ អ្នកលក់ និងអ្នកដឹកជញ្ជូន។"]},
  {number:"១០",id:"content",title:"មាតិកាដែលអ្នកប្រើបង្ហោះ",paragraphs:["អ្នករក្សាកម្មសិទ្ធិលើរូបភាព វីដេអូ អត្ថបទ សារ និងមាតិកាដើមដែលអ្នកបង្ហោះ។ អ្នកធានាថាមានសិទ្ធិប្រើ និងចែករំលែកមាតិកានោះ ហើយវាមិនរំលោភច្បាប់ ឯកជនភាព ឬកម្មសិទ្ធិបញ្ញារបស់អ្នកដទៃ។","ដោយបង្ហោះ អ្នកផ្ដល់ឱ្យ Sesan នូវអាជ្ញាបណ្ណមិនផ្ដាច់មុខ ទូទាំងពិភពលោក មិនគិតថ្លៃ និងអាចផ្ទេរទៅអ្នកផ្ដល់សេវាចាំបាច់ ដើម្បីរក្សាទុក បង្ហាញ កែទំហំ ចែកចាយ និងប្រើមាតិកាសម្រាប់ដំណើរការ ផ្សព្វផ្សាយ និងកែលម្អសេវា។ អាជ្ញាបណ្ណនេះបញ្ចប់ពេលមាតិកាត្រូវបានលុប លើកលែងច្បាប់ Backup ឬកំណត់ត្រាចាំបាច់។"]},
  {number:"១១",id:"reviews",title:"ពិន្ទុវាយតម្លៃ និងមតិយោបល់",paragraphs:["ការវាយតម្លៃត្រូវផ្អែកលើបទពិសោធន៍ពិត ពាក់ព័ន្ធ និងស្មោះត្រង់។ កុំបង្ហោះមតិក្លែងក្លាយ ទទួលប្រាក់ដើម្បីបំភាន់ គំរាមកំហែង បង្ហាញព័ត៌មានឯកជន ឬប្រើភាសារើសអើង។","Sesan អាចត្រួតពិនិត្យ លាក់ ឬលុបការវាយតម្លៃដែលបំពានលក្ខខណ្ឌ ប៉ុន្តែមិនធានាពិនិត្យមាតិកាទាំងអស់មុនបង្ហោះទេ។ ពិន្ទុបង្ហាញមតិរបស់អ្នកប្រើ មិនមែនការធានារបស់ Sesan ទេ។"]},
  {number:"១២",id:"prohibited",title:"សកម្មភាពហាមឃាត់",paragraphs:["អ្នកមិនត្រូវប្រើសេវាសម្រាប់សកម្មភាពខុសច្បាប់ បោកប្រាស់ គ្រោះថ្នាក់ ឬរំខានដល់ប្រព័ន្ធ និងអ្នកដទៃ។"],bullets:["លក់ទំនិញហាមឃាត់ ក្លែងក្លាយ លួច ឬគ្មានសុវត្ថិភាព។","ក្លែងអត្តសញ្ញាណ គណនី ប្រតិបត្តិការ ពិន្ទុ ឬឯកសារ។","ប្រមូលព័ត៌មានអ្នកប្រើដោយគ្មានសិទ្ធិ ឬផ្ញើ Spam។","បង្ហោះមេរោគ Code គ្រោះថ្នាក់ ឬព្យាយាមរំលងសុវត្ថិភាព។","Scrape, reverse engineer ឬប្រើ Bot ដែលបង្កបន្ទុកខុសធម្មតា។","រំលោភសិទ្ធិអ្នកដទៃ គំរាមកំហែង រើសអើង ឬផ្សព្វផ្សាយមាតិកាអាសអាភាសខុសច្បាប់។","បន្លំការទូទាត់ រំលងកម្រៃ ឬប្រើសេវាដើម្បីលាងលុយ។"]},
  {number:"១៣",id:"intellectual-property",title:"កម្មសិទ្ធិបញ្ញារបស់ Sesan",paragraphs:["ឈ្មោះ SESAN, Logo, Brand, ការរចនា App/Website, Software, Code, ក្រាហ្វិក និងមាតិកាដែល Sesan បង្កើត ត្រូវបានការពារដោយច្បាប់កម្មសិទ្ធិបញ្ញា។","យើងផ្ដល់សិទ្ធិមានកម្រិត មិនផ្ដាច់មុខ មិនអាចផ្ទេរ និងអាចដកហូតបាន សម្រាប់ប្រើសេវាតាមលក្ខខណ្ឌនេះ។ អ្នកមិនអាចចម្លង លក់ ផ្ដល់អាជ្ញាបណ្ណ កែប្រែ ឬប្រើ Brand របស់ Sesan ដោយគ្មានការអនុញ្ញាតជាលាយលក្ខណ៍អក្សរ។"]},
  {number:"១៤",id:"availability",title:"ភាពអាចប្រើបាននៃសេវា",paragraphs:["យើងខិតខំរក្សាសេវាឱ្យមានស្ថិរភាព ប៉ុន្តែមិនធានាថានឹងដំណើរការគ្រប់ពេល គ្មាន Error ឬឆ្លើយតបគ្រប់ឧបករណ៍ទេ។ សេវាអាចផ្អាកសម្រាប់ថែទាំ អាប់ដេត សុវត្ថិភាព ឬហេតុការណ៍ក្រៅការគ្រប់គ្រង។","យើងអាចបន្ថែម កែប្រែ ផ្អាក ឬបញ្ឈប់មុខងារ ដោយជូនដំណឹងសមស្របនៅពេលអាចធ្វើបាន។"]},
  {number:"១៥",id:"suspension",title:"ការផ្អាក និងបិទគណនី",paragraphs:["Sesan អាចព្រមាន ដាក់កម្រិត ផ្អាក ឬបិទគណនី/ការផ្សាយ ប្រសិនបើយើងមានមូលហេតុសមស្របថាមានការបំពានលក្ខខណ្ឌ ច្បាប់ សុវត្ថិភាព សិទ្ធិអ្នកដទៃ ឬបង្កហានិភ័យដល់ទីផ្សារ។","អ្នកអាចឈប់ប្រើ ឬស្នើលុបគណនីបាន។ កាតព្វកិច្ចដែលកើតមុនការបិទ ដូចជាបំណុល បញ្ជាទិញ វិវាទ កម្រៃ និងការទទួលខុសត្រូវ នឹងនៅបន្តតាមដែលចាំបាច់។"]},
  {number:"១៦",id:"disclaimer",title:"ការមិនធានា",paragraphs:["ក្នុងកម្រិតដែលច្បាប់អនុញ្ញាត សេវាត្រូវបានផ្ដល់ «តាមស្ថានភាពដែលមាន» និង «តាមភាពអាចរកបាន»។ Sesan មិនធានាភាពត្រឹមត្រូវ គុណភាព សុវត្ថិភាព ភាពស្របច្បាប់ លទ្ធផល ឬភាពសមស្របរបស់ផលិតផល អ្នកប្រើ ឬមាតិកាភាគីទីបីទេ។","អ្នកត្រូវប្រើការវិនិច្ឆ័យផ្ទាល់ខ្លួន ពិនិត្យផលិតផល និងបញ្ជាក់អត្តសញ្ញាណ/លក្ខខណ្ឌមុនប្រតិបត្តិការ។ គ្មានការណែនាំផ្ទាល់មាត់ ឬជាលាយលក្ខណ៍អក្សរណាបង្កើតការធានាដែលមិនមានក្នុងលក្ខខណ្ឌនេះទេ។"]},
  {number:"១៧",id:"liability",title:"ដែនកំណត់នៃការទទួលខុសត្រូវ",paragraphs:["ក្នុងកម្រិតអតិបរមាដែលច្បាប់អនុញ្ញាត Sesan និងបុគ្គលពាក់ព័ន្ធមិនទទួលខុសត្រូវចំពោះការខាតបង់ដោយប្រយោល ពិសេស ដោយចៃដន្យ ផលវិបាក ការបាត់ចំណេញ ទិន្នន័យ អាជីវកម្ម ឬកេរ្តិ៍ឈ្មោះ ដែលកើតពីការប្រើ ឬមិនអាចប្រើសេវា ប្រតិបត្តិការរវាងអ្នកប្រើ ឬមាតិកាភាគីទីបី។","គ្មានអ្វីក្នុងលក្ខខណ្ឌនេះដកហូតការទទួលខុសត្រូវដែលមិនអាចដាក់កម្រិតដោយច្បាប់បានទេ។"]},
  {number:"១៨",id:"law",title:"ច្បាប់គ្រប់គ្រង និងការដោះស្រាយវិវាទ",paragraphs:["លក្ខខណ្ឌនេះត្រូវគ្រប់គ្រងដោយច្បាប់នៃព្រះរាជាណាចក្រកម្ពុជា។ ប្រសិនបើមានវិវាទ សូមទាក់ទង Sesan ជាមុន ដើម្បីព្យាយាមដោះស្រាយដោយសុចរិត។","បើមិនអាចដោះស្រាយបាន វិវាទអាចដាក់ជូនតុលាការ ឬអាជ្ញាធរមានសមត្ថកិច្ចនៅកម្ពុជា តាមច្បាប់អនុវត្ត។"]},
  {number:"១៩",id:"changes",title:"ការកែប្រែលក្ខខណ្ឌ",paragraphs:["យើងអាចកែប្រែលក្ខខណ្ឌនេះដោយសារការផ្លាស់ប្ដូរសេវា អាជីវកម្ម បច្ចេកវិទ្យា ឬច្បាប់។ កំណែថ្មីនឹងបង្ហោះលើ Website ជាមួយកាលបរិច្ឆេទកែចុងក្រោយ។","បើការផ្លាស់ប្ដូរមានសារៈសំខាន់ យើងអាចជូនដំណឹងតាម App, Website ឬព័ត៌មានទំនាក់ទំនង។ ការបន្តប្រើក្រោយកំណែមានប្រសិទ្ធភាពមានន័យថាអ្នកទទួលយកកំណែថ្មី។"]}
];

function TermCard({section}: {section: TermSection}) {
  return <article id={section.id} className="scroll-mt-28 rounded-3xl border border-slate-200 bg-white p-7 shadow-sm sm:p-10"><p className="text-sm font-black text-green-700">ផ្នែកទី {section.number}</p><h2 className="mt-3 text-2xl font-black sm:text-3xl">{section.title}</h2><div className="mt-5 space-y-4 text-base leading-8 text-slate-600 sm:text-lg">{section.paragraphs.map((text,index)=><p key={index}>{text}</p>)}{section.bullets && <ul className="list-disc space-y-2 pl-6 marker:text-green-600">{section.bullets.map(item=><li key={item}>{item}</li>)}</ul>}{section.subsections?.map(sub=><section key={sub.title} className="rounded-2xl bg-slate-50 p-5 sm:p-6"><h3 className="font-black text-slate-900">{sub.title}</h3>{sub.paragraphs?.map((text,index)=><p key={index} className="mt-3">{text}</p>)}{sub.bullets && <ul className="mt-3 list-disc space-y-2 pl-6 marker:text-green-600">{sub.bullets.map(item=><li key={item}>{item}</li>)}</ul>}</section>)}{section.note && <div className="rounded-2xl border border-amber-200 bg-amber-50 p-5 font-bold text-amber-900">{section.note}</div>}</div></article>;
}

export default async function KhmerTermsPage({params}: PageProps) {
  const {locale} = await params;
  if (locale === "en") redirect("/terms");
  if (locale !== "km") notFound();
  return <main className="min-h-screen bg-slate-50 text-slate-950"><header className="sticky top-0 z-50 border-b border-slate-200 bg-white/95 backdrop-blur-xl"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 lg:px-8"><Link href="/km" className="flex items-center gap-3"><img src="/sesan-logo.png" alt="Sesan" className="h-12 w-12 object-contain"/><div><p className="text-xl font-black text-green-700">SESAN</p><p className="text-[9px] font-black tracking-[0.34em] text-amber-500">GROUP</p></div></Link><div className="flex items-center gap-2"><Link href="/terms" className="rounded-full border border-slate-200 px-4 py-2 text-sm font-black text-green-700">English</Link><Link href="/km" className="inline-flex items-center gap-2 rounded-full border border-slate-300 px-4 py-2 text-sm font-bold text-slate-700"><ArrowLeft className="h-4 w-4"/><span className="hidden sm:inline">ត្រឡប់ទៅទំព័រដើម</span></Link></div></div></header><section className="bg-gradient-to-br from-slate-950 via-slate-900 to-emerald-950 px-5 py-24 text-white lg:px-8"><div className="mx-auto max-w-7xl"><div className="inline-flex items-center gap-3 rounded-full border border-white/20 bg-white/10 px-5 py-2.5 text-sm font-black"><FileText className="h-5 w-5"/>ព័ត៌មានផ្លូវច្បាប់</div><h1 className="mt-8 text-5xl font-black sm:text-7xl">លក្ខខណ្ឌប្រើប្រាស់</h1><p className="mt-7 max-w-3xl text-lg leading-9 text-slate-300">លក្ខខណ្ឌពេញលេញសម្រាប់ការប្រើ Sesan App, Sesan Shop, Website, ទីផ្សារឌីជីថល និងសេវាកម្មពាក់ព័ន្ធរបស់ Sesan Group។</p><div className="mt-8 flex flex-wrap gap-3 text-sm font-bold"><span className="rounded-full border border-white/20 bg-white/10 px-4 py-2">ចូលជាធរមាន៖ ៥ សីហា ២០២៦</span><span className="rounded-full border border-white/20 bg-white/10 px-4 py-2">កែចុងក្រោយ៖ ៩ សីហា ២០២៦</span></div></div></section><section className="px-5 py-20 lg:px-8"><div className="mx-auto max-w-5xl"><nav className="mb-8 rounded-3xl border border-green-100 bg-green-50 p-6"><p className="font-black text-green-900">មាតិកា</p><div className="mt-4 grid gap-2 sm:grid-cols-2">{sections.map(section=><a key={section.id} href={`#${section.id}`} className="rounded-xl bg-white px-4 py-3 text-sm font-bold text-slate-700 transition hover:text-green-700">{section.number} · {section.title}</a>)}</div></nav><div className="space-y-6">{sections.map(section=><TermCard key={section.id} section={section}/>)}<div className="rounded-3xl bg-slate-950 p-8 text-white sm:p-10"><p className="text-sm font-black uppercase tracking-wider text-green-400">ទាក់ទង Sesan Group</p><h2 className="mt-3 text-3xl font-black">សំណួរអំពីលក្ខខណ្ឌនេះ?</h2><p className="mt-4 leading-8 text-slate-300">Sesan Group<br/>Website៖ https://sesanshop.com<br/>អ៊ីមែល៖ info@sesanshop.com<br/>អ៊ីមែលបន្ថែម៖ sesanagriculture@gmail.com<br/>ទូរស័ព្ទ៖ +855 11 930 717<br/>ទីតាំង៖ ភ្នំពេញ ប្រទេសកម្ពុជា</p></div></div></div></section></main>;
}
